# Generated by Django 4.1.1 on 2022-09-14 11:43

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('employment_type', models.CharField(choices=[('full-time', 'Full Time'), ('contract', 'Contract'), ('remote', 'Remote'), ('part-time', 'Part Time')], max_length=250)),
                ('experience_level', models.CharField(choices=[('entry-level', 'Entry level'), ('mid-level', 'Mid-level'), ('senior', 'Senior')], max_length=250)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('job_description', models.TextField()),
                ('status', models.CharField(choices=[('unpublished', 'Unpublished'), ('published', 'Published')], default='published', max_length=100)),
                ('date_posted', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('linkedin_profile_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('years_of_experience', models.CharField(choices=[('0 - 1', '0 - 1'), ('1 - 2', '1 - 2'), ('3 - 4', '3 - 4'), ('5 - 6', '5 - 6'), ('7 and above', '7 and above')], max_length=50)),
                ('upload_cv', models.FileField(null=True, upload_to='documents/%Y/%m/%d/')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('time_and_date_applied', models.DateTimeField(auto_now_add=True)),
                ('job_advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job_application', to='jobpostingapp.job_advert')),
            ],
        ),
    ]
